targets:

  ############
  # Framework
  ############

  NetworkCore:
    name: NetworkCore_${platform}
    type: framework
    platform: [iOS, tvOS]

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.myapp.networkCore"
      INFOPLIST_FILE: NetworkCore/Configs/Info.plist

    scheme:
      gatherCovergageData: true
      testTargets:
        - name: NetworkCore_Tests_${platform}
          parallelizable: true
          randomExecutionOrder: true

#    dependencies:
   
    sources:
      - path: Sources
        group: Modules/NetworkCore
      - path: Configs/Info.plist
        group: Modules/NetworkCore

  ############
  # Tests
  ############

  NetworkCore_Tests:
    name: NetworkCore_Tests_${platform}
    type: bundle.unit-test
    platform: [iOS, tvOS]
    settings:
      INFOPLIST_FILE: NetworkCore/Configs/InfoTest.plist
      PRODUCT_BUNDLE_IDENTIFIER: "com.myapp.networkCore.test"
      CODE_SIGN_STYLE: Manual
    sources:
      - path: Tests
        group: Modules/NetworkCore
    dependencies:
      - target: NetworkCore_${platform}

    scheme:
      testTargets:
        - NetworkCore_Tests_${platform}
      gatherCoverageData: true