targets:

  ############
  # Framework
  ############
  
  UICore:
    name: UICore_${platform}
    type: framework
    platform: [iOS, tvOS]

    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.myapp.uicore"
      INFOPLIST_FILE: UICore/Configs/Info.plist

    # dependencies:
    
    sources:
      - path: Sources
        group: Modules/UICore
      - path: Configs/Info.plist
        group: Modules/UICore
